import { useState } from 'react'
import { Building2, CheckCircle2, Trash2 } from 'lucide-react'
import { loadActiveCompany, loadCompanyProfiles, saveActiveCompany, saveCompanyProfiles, upsertCompanyProfile, type CompanyProfile, type SavedCompanyProfile } from '../lib/interviewEngine'

function CompanyField({ label, value, onChange, placeholder }: { label: string; value: string; onChange: (value: string) => void; placeholder: string }) {
    return <label className="block"><span className="mb-1 block text-xs text-muted dark:text-muted-dark">{label}</span><input value={value} onChange={event => onChange(event.target.value)} placeholder={placeholder} className="w-full rounded-lg border border-hairline bg-canvas px-3 py-2.5 text-sm text-ink outline-none focus:border-primary dark:border-hairline-dark dark:bg-canvas-dark dark:text-ink-dark" /></label>
}

export function CompanyProfiles() {
    const [company, setCompany] = useState<CompanyProfile>(loadActiveCompany)
    const [profiles, setProfiles] = useState<SavedCompanyProfile[]>(loadCompanyProfiles)
    const save = () => {
        const next = upsertCompanyProfile(profiles, company, new Date().toLocaleDateString('zh-CN'))
        setProfiles(next); saveCompanyProfiles(next); saveActiveCompany(company)
    }
    const select = (profile: SavedCompanyProfile) => { setCompany(profile.company); saveActiveCompany(profile.company) }
    const remove = (id: string) => { const next = profiles.filter(profile => profile.id !== id); setProfiles(next); saveCompanyProfiles(next) }

    return <main className="mx-auto max-w-screen-md px-4 pb-10 pt-20"><section className="rounded-2xl border border-hairline bg-card p-5 dark:border-hairline-dark dark:bg-card-dark"><div className="flex items-center gap-3"><div className="rounded-xl bg-primary/15 p-2.5"><Building2 className="h-5 w-5 text-primary" /></div><div><p className="text-xs font-medium text-primary">本地公司画像</p><h2 className="font-display text-2xl text-ink dark:text-ink-dark">公司与岗位</h2></div></div><p className="mt-3 text-sm text-body dark:text-body-dark">保存后会作为下一场模拟面试的公司背景，用于调整考察重点。</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><CompanyField label="公司名称" value={company.name} onChange={value => setCompany({ ...company, name: value })} placeholder="例如：某支付平台" /><CompanyField label="行业 / 业务" value={company.industry} onChange={value => setCompany({ ...company, industry: value })} placeholder="支付、电商、SaaS" /><CompanyField label="公司规模" value={company.size} onChange={value => setCompany({ ...company, size: value })} placeholder="500-1000 人" /><CompanyField label="发展阶段" value={company.stage} onChange={value => setCompany({ ...company, stage: value })} placeholder="成长期、成熟期" /><CompanyField label="技术文化" value={company.culture} onChange={value => setCompany({ ...company, culture: value })} placeholder="工程质量、高可用优先" /><CompanyField label="招聘偏好" value={company.hiringPreferences || ''} onChange={value => setCompany({ ...company, hiringPreferences: value })} placeholder="稳定性、主人翁意识" /></div><button onClick={save} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-3 text-sm font-medium text-white"><CheckCircle2 className="h-4 w-4" />保存并设为当前公司</button></section><section className="mt-4 rounded-2xl border border-hairline bg-canvas p-5 dark:border-hairline-dark dark:bg-canvas-dark"><h3 className="font-semibold text-ink dark:text-ink-dark">已保存公司</h3>{profiles.length ? <div className="mt-3 space-y-2">{profiles.map(profile => <div key={profile.id} className="flex items-center justify-between gap-3 rounded-lg bg-soft p-3 dark:bg-soft-dark"><button onClick={() => select(profile)} className="min-w-0 text-left"><p className="text-sm font-medium text-ink dark:text-ink-dark">{profile.company.name}</p><p className="mt-1 truncate text-xs text-muted dark:text-muted-dark">{profile.company.industry || '未填写行业'} · {profile.company.stage || '未填写阶段'}</p></button><button onClick={() => remove(profile.id)} className="rounded-lg p-2 text-red-600 dark:text-red-400" aria-label="删除公司"><Trash2 className="h-4 w-4" /></button></div>)}</div> : <p className="mt-3 text-sm text-muted dark:text-muted-dark">尚未保存公司画像。</p>}</section></main>
}
